import { z } from "zod";

export const SaveSessionSummaryInputSchema = z.object({
  session_id: z.string().describe("The ID of the session being summarized."),
  summary: z.string().describe("The detailed, technical summary generated by the AI."),
});

export type SaveSessionSummaryInput = z.infer<typeof SaveSessionSummaryInputSchema>;

/**
 * @description Saves a generated summary for a specific session ID into the database.
 * This should be called immediately after generating the summary instructed by `summarize_previous_session`.
 * 
 * @param input The session ID and the detailed summary text.
 * @returns A confirmation string if successful.
 */
export async function saveSessionSummary(input: SaveSessionSummaryInput): Promise<string> {
  throw new Error("Not implemented");
}
